### ISSUE TITLE
Parsing of top/bottom orientation for players is not accurate when spectating

### ISSUE THREAD

**Issue by Lange** [Tespa/hearthstone-parser#1]
When spectating, I've yet to find a reliable way of determining which player is on the top of the screen and which player is on the bottom of the screen.

I can reliably determine the names of the players, as well as whose turn it is. What I don't know is how to figure out where the players are geographically located on the playing field.

Determining player position when consuming a game log from one of the players seems straightforward. This issue is specifically focused on game logs consumed from *spectators*.

**Comment by Lange** [comment]
Our current understanding is that fixing this may require reading game memory. There seems to be a precedent for this in other tools. @rikumiyao has the details.

**Comment by rikumiyao** [comment]
#32
