### ISSUE TITLE
Turn booleans are sometimes (always?) not updated for the first turn

### ISSUE THREAD

**Issue by Lange** [Tespa/hearthstone-parser#25]
It seems that we're not properly updating the `player.turn` booleans for the first turn in a given match. Not sure what the fix is.

**Comment by rikumiyao** [comment]
Oh I noticed this too, I think the same event used to update whether we are in mulligan or not (`BEGIN_TURN` I think) can be used. I am also planning to use that event for turn timers too, and will start working on it.

**Comment by Lange** [comment]
Fixed by https://github.com/Tespa/hearthstone-parser/pull/27
